/**
 * Generated by anjay_codegen.py on 2023-11-15 09:29:44
 *
 * LwM2M Object: Time
 * ID: 3333, URN: urn:oma:lwm2m:ext:3333, Optional, Multiple
 *
 * This IPSO object is used to report the current time in seconds since
 * January 1, 1970 UTC. There is also a fractional time counter that has
 * a range of less than one second.
 */
#ifndef TIME_OBJECT_H
#define TIME_OBJECT_H

#include <anjay/dm.h>

const anjay_dm_object_def_t **time_object_create(void);
void time_object_release(const anjay_dm_object_def_t **def);
void time_object_notify(anjay_t *anjay, const anjay_dm_object_def_t **def);
void time_object_send(anjay_t *anjay, const anjay_dm_object_def_t **def);

#endif // TIME_OBJECT_H
